* Task 1
  Построить семантическую модель (сеть) представления знаний в предметной области «Информационные системы» (виды и функционирование).

** 1)
   Ключевые понятия данной предметной области - Информационная система, тот кто пользуется информационной системой(пользователь), данные внутри ИС, и способ взаимодействия с ИС(пользовательский интерфейс). Исходя из этого, вершины графа будут следующими: "ИС" "Человек" "Администратор" "Пользователь" "Данные" "Исходные данные" "Обработанные данные"
** 2)
   У этих объектов есть определенные свойства и атрибуты. Например Информационные системы имеют определенные системные требования, каждая запись в ИС занимает определенное количество памяти. Поэтому добавим вершины "Системные требования" и "Память".
** 3)
   Определим для имеющихся вершин отношения и их типы, испольщуя таблицу 2.
** 4)
   Добавим знание о конкретных фактах решаемой задачи. Пусть имеется две Информационные системы: ClickHouse и Firebird. Первый использует специальное Api, а второй SQL язык. Омар решил использовать Firebird и сделать три записи: таблицу со списком одногруппников - 2mb , таблицу со списком преподавателей - 1mb и таблицу со списком предметов - 1mb. Исходя их этого добавим соответствующие вершины в граф и соединим их функциональными отношениями и отношениями типо "например или является экземпляром". Полученный в результате граф изображен на рисунке 1.
** 5)
   Осуществим проверку установленных связей. Например возьмем вершину "Данные" и пройдем по установленным связям. Получаем следующую информацию: Данные
