* Task 4)
  Описать функционирование одной эпохи генетического алгоритма на примере произвольной задачи (не менее пяти признаков закодировать случайным образом, начальная популяция содержит не менее 10 особей). Использовать следующие параметры генетического алгоритма: фитнесс- функция – сумма всех бит особи, деленная на количество особей в популяции; метод отбора – турнирный с использованием принципа элитизма; оператор скрещивания – равномерный кроссовер; оператор мутации – одноточечная мутация.

* Решение
  Фенотип(задаем десятичные значения случайным образом)
| Признак   | Двоичное | Десятичное |  Код |
|           | значение |   значение | Грея |
|           | признака |   признака |      |
|-----------+----------+------------+------|
| Признак 1 |     0000 |          0 | 0000 |
| Признак 2 |     1010 |         10 | 1111 |
| Признак 3 |     1111 |         15 | 1000 |
| Признак 4 |     1110 |         14 | 1001 |
| Признак 5 |     0010 |          2 | 0011 |
| Признак 6 |     0001 |          1 | 0001 |
|           |          |            |      |
  
** Шаг 1
   Определено шесть признаков, пусть особь содержит любые 3 из них(два первых -значения первого критерия, четыре последних второго), случайным образом сгенерируем 10 особей, каждая длиной 8бит

Особь 1: 00001111
Особь 2: 00001110
Особь 3: 10011111
Особь 4: 00000010
Особь 5: 00000001
Особь 6: 10101111
Особь 7: 10101110
Особь 8: 10100010
Особь 9: 10100001
Особь 10: 10011001

** Шаг 2
   | Особь |   Сумма |      Приспо |
   |       |     бит | собленность |
   |       | в особи |       особи |
   |-------+---------+-------------|
   |     1 |       4 |         0.4 |
   |     2 |       3 |         0.3 |
   |     3 |       6 |         0.6 |
   |     4 |       1 |         0.1 |
   |     5 |       1 |         0.1 |
   |     6 |       6 |         0.6 |
   |     7 |       5 |         0.5 |
   |     8 |       3 |         0.3 |
   |     9 |       3 |         0.3 |
   |    10 |       4 |         0.4 |
   |       |         |             |
   
Среднее значение суммы бит в популяции = 3.6

** 3 Шаг Отбор(используется метод отбора - турнирный с принципом элитизма)
   Пусть после тура образовались пары
   1-3, 3-6,7-8,9-10
** 4 Шаг Скрещивание
   Раномерный кроссовер (используем случайный подброс монетки)
   Особь 1: 00001111   Особь 2.1: 10001111
   Особь 3: 10011111   Особь 2.2: 00011111

   Особь 3: 10011111   Особь 2.3: 10111111
   Особь 6: 10101111   Особь 2.4: 10001111

   Особь 7: 10101110   Особь 2.5: 10100110
   Особь 8: 10100010   Особь 2.6: 10101010

   Особь 9:  10100001   Особь 2.7: 10110001
   Особь 10: 10011001   Особь 2.8: 10001001
Таким образом получили 8 особей новой популяции

** Шаг 5 Мутация (Используется оператор - одноточечная мутация)
   Определим вероятность мутации 40% и бит - пятый, подвергающийся мутации
| Особь | Cлуч. |    Особь |   Мутир. |
|       | число |          |    особь |
|-------+-------+----------+----------|
|     1 |    56 | 00001111 |          |
|     2 |     8 | 00001110 | 00001010 |
|     3 |    22 | 10011111 | 10010111 |
|     4 |    90 | 00000010 |          |
|     5 |    71 | 00000001 |          |
|     6 |    29 | 10101111 | 10100111 |
|     7 |    13 | 10101110 | 10100110 |
|     8 |    85 | 10100010 |          |
|     9 |    88 | 10100001 |          |
|    10 |    46 | 10011001 |          |
|       |       |          |          |

** Шаг 6 Формирование новой популяции
   Особь 2.1: 10001111 
   Особь 2.2: 00011111 
   Особь 2.3: 10111111 
   Особь 2.4: 10001111 
   Особь 2.5: 10100110 
   Особь 2.6: 10101010 
   Особь 2.7: 10110001
   Особь 2.8: 10001001
   Особь 2.9: 00001010
   Особь 2.10: 10010111
   Особь 2.11: 10100111
   Особь 2.12: 10100110
   Особь 2.13: 10101111
   1-8 - наследники, 9-12 мутировавшие особи, 13 - одна особь с максимальной приспособленностью
